???prompt PL/SQL Developer Export User Objects for user SYSTEM@ORCL
prompt Created by dell on 2019Äê5ÔÂ18ÈÕ
set define off
spool tb_order.log

prompt
prompt Creating table TB_ORDER
prompt =======================
prompt
create table SYSTEM.TB_ORDER
(
  id         NUMBER generated by default on null as identity,
  username   VARCHAR2(20),
  title      VARCHAR2(40),
  ordernum   NUMBER,
  price      VARCHAR2(20),
  totalprice VARCHAR2(40),
  ordertime  VARCHAR2(50)
)
tablespace SYSTEM
  pctfree 10
  pctused 40
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table SYSTEM.TB_ORDER
  add constraint ORDERID primary key (ID)
  using index 
  tablespace SYSTEM
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );


prompt Done
spool off
set define on
