???prompt PL/SQL Developer Export User Objects for user SYSTEM@ORCL
prompt Created by dell on 2019Äê5ÔÂ18ÈÕ
set define off
spool tb_userInfo.log

prompt
prompt Creating table TB_USERINFO
prompt ==========================
prompt
create table SYSTEM.TB_USERINFO
(
  id           NUMBER generated by default on null as identity,
  nickname     VARCHAR2(40),
  sex          VARCHAR2(10),
  birthday     VARCHAR2(40),
  introduction VARCHAR2(100),
  phone        VARCHAR2(20),
  username     VARCHAR2(20)
)
tablespace SYSTEM
  pctfree 10
  pctused 40
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table SYSTEM.TB_USERINFO
  add constraint USERINFOID primary key (ID)
  using index 
  tablespace SYSTEM
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );


prompt Done
spool off
set define on
